# Generated by Django 5.2.1 on 2025-06-15 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_thread_created_by'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='check_review_context',
        ),
        migrations.AddField(
            model_name='review',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='review_type',
            field=models.CharField(choices=[('pr', 'Pull Request'), ('commit', 'Commit'), ('vscode', 'VS Code Extension'), ('manual', 'Manual Review')], default='pr', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='thread_id',
            field=models.CharField(blank=True, help_text='LangGraph thread ID for this review', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.repository'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('pull_request__isnull', False), ('commit__isnull', False), ('review_type', 'vscode'), ('review_type', 'manual'), _connector='OR'), name='check_review_context'),
        ),
    ]
